Repository nextcloud/firstrunwizard, pull requests merged in 2018-05, with the labels that each got.

#57 Make the first run wizard more helpful
  css/firstrunwizard.css
  css/firstrunwizard.scss
  img/appstore.png
  img/world.svg
  js/activate.js
  js/firstrunwizard.js
  templates/page.apps.php
  templates/page.clients.php
  templates/page.final.php
  templates/page.values.php
  templates/wizard.php
Labels: 3. to review, design, enhancement

#60 Move tests to drone
  .drone.yml
  .travis.yml
  appinfo/info.xml
  tests/Controller/WizardControllerTest.php
Labels: 3. to review

#63 Add about entry to settings menu
  appinfo/app.php
  css/colorbox.scss
  css/firstrunwizard.scss
  js/firstrunwizard.js
  lib/AppInfo/Application.php
Labels: 3. to review, design, enhancement

#64 Move navigation registration to appinfo.xml
  appinfo/app.php
  appinfo/info.xml
  img/info.svg
  js/firstrunwizard.js
  lib/AppInfo/Application.php
Labels: 4. to release, enhancement

#65 Remove first run wizard from client settings section
  templates/personal-settings.php
Labels: 3. to review, design

#66 Use empty route for about menu entry
  appinfo/info.xml
Labels: 3. to review, bug

#68 Fixes for template texts
  templates/page.apps.php
  templates/page.final.php
  templates/page.values.php
  templates/personal-settings.php
Labels: 2. developing, bug
