Repository nextcloud/firstrunwizard, pull requests merged in 2019-03, with the labels that each got.

#175 Bring back tiny css file for the personal page
  css/personalsettings.css
  templates/personal-settings.php
Labels: 3. to review

#178 use nextcloud-vue's modal
  js/firstrunwizard.js
  js/firstrunwizard.js.map
  package-lock.json
  package.json
  src/App.vue
  src/main.js
Labels: 3. to review, design

#181 Only load apps page for admins
  lib/Controller/WizardController.php
  tests/Controller/WizardControllerTest.php
Labels: 3. to review, bug

#182 Fix next arrow on light theming colors
  js/firstrunwizard.js
  js/firstrunwizard.js.map
  src/App.vue
Labels: 3. to review, bug
