Repository nextcloud/firstrunwizard, pull requests merged in 2019-01, with the labels that each got.

#99 Update docker images for PHP 7.1+
  .drone.yml
  tests/Notification/NotifierTest.php
  tests/bootstrap.php
Labels: 3. to review

#98 Hide appstore when disabled
  lib/Controller/WizardController.php
  templates/wizard.php
  tests/Controller/WizardControllerTest.php
Labels: 4. to release

#104 Avoid double encoding in slogan
  templates/wizard.php
Labels: 3. to review, bug

#103 Use target="_blank" and rel="noreferrer noopener"
  templates/page.apps.php
  templates/page.clients.php
  templates/page.final.php
  templates/page.values.php
  templates/personal-settings.php
Labels: 3. to review, bug

#106 Move to vue
  .babelrc.js
  .drone.yml
  .eslintrc.js
  .gitignore
  Makefile
  css/colorbox.scss
  css/firstrunwizard.scss
  img/intro.png
  img/world.svg
  js/about.js
  js/activate.js
  js/firstrunwizard.js
  js/jquery.colorbox.js
  lib/AppInfo/Application.php
  lib/Controller/WizardController.php
  package-lock.json
  package.json
  src/App.vue
  src/main.js
  templates/page.final.php
  templates/page.intro.php
  templates/page.values.php
  tests/Controller/WizardControllerTest.php
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: 3. to review

#117 Add screenshot and instructions to readme
  README.md
Labels: 3. to review

#116 Check if vue build is committed
  .drone.yml
  .gitattributes
  .gitignore
  js/firstrunwizard.js
  js/firstrunwizard.js.map
  webpack.common.js
Labels: 3. to review
