Repository nextcloud/firstrunwizard, pull requests merged in 2019-02, with the labels that each got.

#134 Only add event listener if selector can be found
  js/about.js
Labels: 3. to review, bug

#136 Use EVENT_LOAD_ADDITIONAL_SCRIPTS_LOGGEDIN to add script
  lib/AppInfo/Application.php
Labels: 3. to review

#149 Use node container for eslint as well
  .drone.yml
Labels: 3. to review

#141 add link to macos/ios configuration profile
  lib/Controller/WizardController.php
  templates/page.clients.php
  templates/personal-settings.php
Labels: 3. to review, enhancement

#150 Do not load firstrunwizard on settings page
  templates/personal-settings.php
Labels: 3. to review, bug

#157 Reverse animation when navigating backwards
  js/firstrunwizard.js
  js/firstrunwizard.js.map
  src/App.vue
Labels: 4. to release, papercut

#135 Revert "Use image instead on inline embedding for intro image"
  js/firstrunwizard.js
  js/firstrunwizard.js.map
  src/App.vue
  templates/page.intro.php
Labels: 3. to review
