Repository nextcloud/firstrunwizard, pull requests merged in 2019-11, with the labels that each got.

#218 Query Application class from server container
  appinfo/app.php
Labels: 4. to release

#219 security@nextcloud.com is not monitored and mails are dropped
  .github/contributing.md
Labels: 3. to review, technical debt

#220 Adjust info icon style to other icons
  img/app.svg
  img/info.svg
Labels: 3. to review, design, enhancement
