Repository nextcloud/firstrunwizard, pull requests merged in 2021-11, with the labels that each got.

#634 Update version on master
  appinfo/info.xml
Labels: 4. to release

#635 Update npm and node engines versions
  package.json
Labels: dependencies

#632 disable fade-out because of accessbility reasons
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.map
  src/App.vue
Labels: enhancement, 3. to review

#644 New intro files
  img/Nextcloud.mp4
  img/Nextcloud.webm
Labels: 3. to review, backport-request
