Repository nextcloud/firstrunwizard, pull requests merged in 2022-04, with the labels that each got.

#680 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#681 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#682 Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#683 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#691 make the buttons round
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.map
  src/App.vue
Labels: 3. to review

#692 disable social recommendation
  lib/Notification/AppHint.php
  lib/Notification/Notifier.php
Labels: 3. to review, backport-request

#696 Fix settings navigation order
  appinfo/info.xml
Labels: 3. to review, backport-request, regression

#697 [stable23] Fix settings navigation order
  appinfo/info.xml
Labels: 3. to review, backport-request
