Repository nextcloud/firstrunwizard, pull requests merged in 2022-12, with the labels that each got.

#789 fix background image size
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.map
  src/App.vue
Labels: bug, 3. to review, backport-request

#788 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#794 Revert removing static js files
  js/about.js
  js/activate.js
  js/personalsettings.js
  webpack.js
Labels: 3. to review, regression, javascript

#799 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
