Repository nextcloud/firstrunwizard, pull requests merged in 2022-08, with the labels that each got.

#724 Update npm and node engines versions
  package.json
Labels: dependencies

#725 Port away from serve side scss
  css/personalsettings.css
  css/personalsettings.scss
Labels: 3. to review

#731 Fix theming usage
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.map
  src/App.vue
  webpack.js
Labels: bug, 3. to review
