Repository nextcloud/firstrunwizard, pull requests merged in 2022-11, with the labels that each got.

#750 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#753 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#752 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#780 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#778 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#762 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#764 Updating lint-stylelint.yml workflow from template
  .github/workflows/lint-stylelint.yml
Labels: dependencies

#765 Updating lint-php-cs.yml workflow from template
  .github/workflows/lint-php-cs.yml
Labels: dependencies

#768 Updating phpunit-pgsql.yml workflow from template
  .github/workflows/phpunit-pgsql.yml
Labels: dependencies

#769 Updating phpunit-sqlite.yml workflow from template
  .github/workflows/phpunit-sqlite.yml
Labels: dependencies

#767 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#766 Updating phpunit-oci.yml workflow from template
  .github/workflows/phpunit-oci.yml
Labels: dependencies

#783 Fix navigation menu order
  appinfo/info.xml
Labels: bug, 3. to review, backport-request, regression
