Repository nextcloud/firstrunwizard, pull requests merged in 2022-09, with the labels that each got.

#737 fix modal on mobile and a button
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.map
  src/App.vue
Labels: 3. to review, ui-refresh-feedback

#738 Update page.final.php
  templates/page.final.php
Labels: 3. to review

#739 Update recommended apps for 25
  img/apps/forms.svg
  img/apps/recognize.svg
  lib/Notification/AppHint.php
  lib/Notification/Notifier.php
Labels: 3. to review

#740 remove freenode chat from final page of frw
  templates/page.final.php
Labels: enhancement, 3. to review
