Repository nextcloud/firstrunwizard, pull requests merged in 2022-01, with the labels that each got.

#660 Create block-merge-freeze.yml
  .github/workflows/block-merge-freeze.yml
Labels: backport-request

#668 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#664 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#672 CI update
  .drone.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/oci.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .gitignore
  .php-cs-fixer.dist.php
  appinfo/info.xml
  composer.json
  composer.lock
  js/about.js
  lib/AppInfo/Application.php
  lib/Controller/WizardController.php
  lib/Notification/AppHint.php
  lib/Notification/BackgroundJob.php
  lib/Notification/Notifier.php
  lib/Settings/Personal.php
  templates/page.clients.php
  templates/personal-settings.php
  tests/AppInfo/ApplicationTest.php
  tests/AppInfo/RoutesTest.php
  tests/Controller/WizardControllerTest.php
  tests/Notification/BackgroundJobTest.php
  tests/Notification/NotifierTest.php
Labels: 3. to review, technical debt
