Repository nextcloud/firstrunwizard, pull requests merged in 2023-07, with the labels that each got.

#903 [master] Fix npm audit
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.map
  package-lock.json
Labels: 4. to release, dependencies

#906 [stable27] Fix npm audit
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.map
  package-lock.json
Labels: 4. to release, dependencies

#904 [stable26] Fix npm audit
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.map
  package-lock.json
Labels: 4. to release, dependencies

#901 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#917 Create pr-feedback.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review

#914 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#905 [stable24] Fix npm audit
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.LICENSE.txt
  js/firstrunwizard-main.js.map
  package-lock.json
Labels: 3. to review, dependencies

#902 chore: update node engines to next LTS
  package.json
Labels: 3. to review, dependencies, automated

#907 [stable25] Fix npm audit
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.LICENSE.txt
  js/firstrunwizard-main.js.map
  package-lock.json
  src/App.vue
Labels: 3. to review, dependencies

#926 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#930 [stable24] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#929 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#927 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#928 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
