Repository nextcloud/firstrunwizard, pull requests merged in 2023-02, with the labels that each got.

#825 feat(app-hints): Avoid sending app hints if the appstore is disabled
  lib/Listener/BeforeTemplateRenderedListener.php
Labels: 3. to review

#816 Mount menu entry into Vue user menu
  appinfo/info.xml
  js/about.js
Labels: enhancement, 4. to release, backport-request, accessibility

#824 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#829 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#832 Bump @nextcloud/vue from 7.5.0 to 7.7.1
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.map
  package-lock.json
  package.json
Labels: bug, 4. to release, backport-request
