Repository nextcloud/firstrunwizard, pull requests merged in 2023-08, with the labels that each got.

#931 [stable27] chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review

#932 [stable26] chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/update-nextcloud-ocp.yml
  tests/Notification/NotifierTest.php
Labels: 4. to release

#925 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#933 [stable25] chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/update-nextcloud-ocp.yml
  composer.json
  tests/Controller/WizardControllerTest.php
Labels: 4. to release

#900 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 4. to release, dependencies
