Repository nextcloud/firstrunwizard, pull requests merged in 2023-06, with the labels that each got.

#877 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/update-nextcloud-ocp.yml
  tests/Notification/NotifierTest.php
Labels: 4. to release, dependencies, automated

#881 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#880 update dependabot config
  .github/dependabot.yml
Labels: 3. to review, dependencies

#852 add headings for slides
  src/App.vue
  templates/page.apps.php
  templates/page.clients.php
  templates/page.final.php
  templates/page.values.php
Labels: enhancement, design, 3. to review

#891 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#893 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#892 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
