Repository nextcloud/firstrunwizard, pull requests merged in 2023-04, with the labels that each got.

#856 chore(maintainers): Update CODEOWNERS file
  .github/CODEOWNERS
Labels: 3. to review

#859 add npm-audit-fix
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review

#862 [stable26] Fix npm audit
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.map
  package-lock.json
Labels: 4. to release, dependencies

#860 [stable25] Fix npm audit
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.map
  package-lock.json
Labels: 4. to release, dependencies

#864 [stable24] Pin postgres image
  .github/workflows/phpunit-pgsql.yml
Labels: 3. to review

#861 [stable24] Fix npm audit
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.map
  package-lock.json
Labels: 3. to review, dependencies
