Repository nextcloud/firstrunwizard, pull requests merged in 2023-05, with the labels that each got.

#842 [stable26] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 4. to release, dependencies

#819 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 4. to release, dependencies

#830 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 4. to release, dependencies

#867 Use the color-primary-element* variables
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.map
  src/App.vue
  src/components/IntroVideo.vue
Labels: bug, design, 3. to review

#871 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 4. to release, dependencies

#870 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 4. to release, dependencies

#874 [stable27] chore(CI): Adjust testing matrix for Nextcloud 27 on stable27
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
Labels: 3. to review, dependencies

#875 feat(deps): Add Nextcloud 28 support on master
  .github/workflows/npm-audit-fix.yml
  .github/workflows/update-nextcloud-ocp.yml
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#879 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 4. to release, dependencies

#878 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 4. to release, dependencies
