Repository nextcloud/firstrunwizard, pull requests merged in 2023-11, with the labels that each got.

#960 New first run wizard
  .gitignore
  css/personalsettings.css
  img/Nextcloud.mp4
  img/Nextcloud.webm
  img/androidBadge.png
  img/appstore.png
  img/intro.png
  img/iosBadge.png
  img/nextcloudLogo.svg
  img/user.svg
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.LICENSE.txt
  package-lock.json
  package.json
  src/App.vue
  src/components/AppStoreBadge.vue
  src/components/Card.vue
  src/components/IntroImage.vue
  src/components/IntroVideo.vue
  src/components/Page0.vue
  src/components/Page1.vue
  src/components/Page2.vue
  src/components/Page3.vue
  src/components/pageStyles.scss
  templates/page.apps.php
  templates/page.clients.php
  templates/page.final.php
  templates/page.intro.php
  templates/page.values.php
  templates/personal-settings.php
  tests/Controller/WizardControllerTest.php
Labels: enhancement, design, 3. to review

#994 Restore user.svg icon as it's still used in notifications
  img/user.svg
Labels: bug, 3. to review

#1001 [stable25] Fix npm audit
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.map
  package-lock.json
Labels: 3. to review, dependencies

#999 [stable26] Fix npm audit
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1000 [stable27] Fix npm audit
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.map
  package-lock.json
Labels: 3. to review, dependencies
