Repository nextcloud/firstrunwizard, pull requests merged in 2023-01, with the labels that each got.

#811 chore(CI): Update master php testing versions and workflow templates
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-when-unrelated.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/update-nextcloud-ocp.yml
  .gitignore
  composer.json
  composer.lock
  tests/Controller/WizardControllerTest.php
Labels: 3. to review

#812 Set native tooltip and notification on "copy link" button. Remove cus…
  js/personalsettings.js
Labels: 3. to review

#807 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#802 [stable23] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#815 Upgrade @nextcloud/vue from 5.4.0 to 7.5.0
  js/firstrunwizard-main.js
  js/firstrunwizard-main.js.LICENSE.txt
  js/firstrunwizard-main.js.map
  package-lock.json
  package.json
  src/App.vue
Labels: enhancement, 4. to release, backport-request, accessibility

#821 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#820 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
