Repository nextcloud/firstrunwizard, pull requests merged in 2024-01, with the labels that each got.

#1027 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1026 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#997 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1020 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1044 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1042 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1045 chore: Bump vimeo/psalm to fix locked psr/container
  composer.json
  composer.lock
Labels: 3. to review

#1054 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1056 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1055 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1053 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1052 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1061 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1071 fix deprecated warning
  lib/Settings/Personal.php
Labels: 3. to review

#1070 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
