Repository nextcloud/firstrunwizard, pull requests merged in 2024-09, with the labels that each got.

#1344 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1345 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1353 fix: Add app hint for whiteboard
  lib/Notification/AppHint.php
  lib/Notification/Notifier.php
Labels: bug, 3. to review

#1351 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1356 Shorder and more consistent wordings (compared to others)
  lib/Notification/Notifier.php
Labels: enhancement, design, 3. to review

#1363 fix: Add missing whiteboard icon
  REUSE.toml
  img/apps/whiteboard.svg
Labels: bug, 3. to review, backport-request

#1378 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1377 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1376 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1379 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
