Repository nextcloud/firstrunwizard, pull requests merged in 2024-06, with the labels that each got.

#1235 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1237 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1239 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#1238 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1246 Update icons to Material Symbols
  img/app.svg
  img/apps/calendar.svg
  img/apps/contacts.svg
  img/apps/groupfolders.svg
  img/apps/mail.svg
  img/apps/notes.svg
  img/apps/social.svg
  img/apps/tasks.svg
  img/facebook.svg
  img/info.svg
  img/user.svg
Labels: design, 3. to review

#1243 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1236 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1245 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1255 [master] Fix npm audit
  js/firstrunwizard-about.mjs
  js/firstrunwizard-activate.mjs
  js/main-BYoL_izH.mjs
  js/main-BniTI64H.mjs
  package-lock.json
Labels: 3. to review, dependencies

#1254 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1267 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1257 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1258 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1256 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1244 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
