Repository nextcloud/firstrunwizard, pull requests merged in 2024-08, with the labels that each got.

#1288 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1299 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1300 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1301 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1295 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1260 fix: Remove legacy code that caused errors
  appinfo/routes.php
  lib/Controller/WizardController.php
  templates/personal-settings.php
  tests/AppInfo/ApplicationTest.php
  tests/AppInfo/RoutesTest.php
  tests/Controller/WizardControllerTest.php
Labels: bug, 3. to review

#1287 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1304 chore: Add new animation with updated icons
  img/Nextcloud.mp4
  img/Nextcloud.webm
Labels: design, 3. to review

#1307 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1306 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1309 feat(deps): Add Nextcloud 31 support on master
  .github/dependabot.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/update-nextcloud-ocp.yml
  appinfo/info.xml
  js/firstrunwizard-about.mjs.license
  js/firstrunwizard-about.mjs.map.license
  js/firstrunwizard-activate.mjs.license
  js/firstrunwizard-activate.mjs.map.license
  js/firstrunwizard-settings.mjs.license
  js/firstrunwizard-settings.mjs.map.license
  js/main-Bs75fxKL.chunk.mjs.license
  js/main-Bs75fxKL.chunk.mjs.map.license
  package-lock.json
  package.json
Labels: 3. to review

#1318 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1324 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/reuse.yml
Labels: 3. to review, dependencies, automated

#1334 [stable30] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1333 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
