Repository nextcloud/firstrunwizard, pull requests merged in 2024-02, with the labels that each got.

#1081 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1082 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#1083 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1084 [stable28] chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1062 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1090 chore: Migrate to OCP version of QueuedJob
  lib/Notification/BackgroundJob.php
  tests/Notification/BackgroundJobTest.php
Labels: 3. to review

#1089 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1094 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1103 fix: Replace deprecated code
  lib/AppInfo/Application.php
  lib/Listener/AppEnabledListener.php
Labels: bug, 3. to review

#1105 feat: Add psalm workflow and adjust code
  .github/workflows/psalm.yml
  composer.json
  composer.lock
  lib/Controller/WizardController.php
  lib/Listener/BeforeTemplateRenderedListener.php
  lib/Notification/Notifier.php
  lib/Settings/Personal.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/stubs/oc_template.php
Labels: 3. to review

#1108 fix: Remove old unused code
  appinfo/routes.php
  lib/Controller/WizardController.php
  tests/AppInfo/RoutesTest.php
  tests/Controller/WizardControllerTest.php
Labels: 3. to review
