Repository nextcloud/firstrunwizard, pull requests merged in 2024-04, with the labels that each got.

#1141 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1143 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1142 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1132 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1161 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1159 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1160 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 4. to release, dependencies

#1173 [master] Fix npm audit
  js/firstrunwizard-about.mjs
  js/firstrunwizard-activate.mjs
  js/main-nD_9sdBo.mjs
  js/main-rS92LHob.mjs
  js/vendor.LICENSE.txt
  package-lock.json
Labels: 3. to review, dependencies

#1170 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1169 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1176 fix(i18n): Fixed typo
  js/firstrunwizard-about.mjs
  js/firstrunwizard-activate.mjs
  js/main-TLYkAnT0.mjs
  js/main-sGRl38Rj.mjs
  src/components/pages/SharePage.vue
Labels: backport-request

#1180 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1185 fix: Apply class to wizard page title (was a typo) and correctly navigate to page whats-new page
  js/firstrunwizard-about.mjs
  js/firstrunwizard-activate.mjs
  js/main-CezsHINt.mjs
  js/main-TLYkAnT0.mjs
  src/components/WizardPage.vue
  src/pages.ts
Labels: bug, 3. to review, backport-request
