Repository nextcloud/firstrunwizard, pull requests merged in 2024-07, with the labels that each got.

#1272 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1273 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1275 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#1280 Migrate REUSE to TOML format
  .reuse/dep5
  REUSE.toml
Labels: 4. to release, technical debt

#1279 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1285 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1286 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1296 [stable29] Fix npm audit
  js/firstrunwizard-about.mjs
  js/firstrunwizard-about.mjs.map
  js/firstrunwizard-activate.mjs
  js/firstrunwizard-activate.mjs.map
  js/main-BR4qyIrQ.mjs
  js/main.chunk.mjs
  js/modulepreload-polyfill-DDskOgo1.mjs
  js/modulepreload-polyfill-DDskOgo1.mjs.map
  js/modulepreload-polyfill.chunk.mjs
  js/modulepreload-polyfill.chunk.mjs.map
  package-lock.json
Labels: 3. to review, dependencies

#1292 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
